In [3]:
import numpy as np

In [4]:
np.__version__

'2.3.1'

In [5]:
lst = [1,2,3,4,5,5,6,6]  ###list , array
arr =np.array(lst)

In [6]:
arr

array([1, 2, 3, 4, 5, 5, 6, 6])

In [7]:
np.array([1,2,3,4,5,5,6,6,7,8,8])

array([1, 2, 3, 4, 5, 5, 6, 6, 7, 8, 8])

In [8]:
arr

array([1, 2, 3, 4, 5, 5, 6, 6])

In [9]:
lst =[1,2,3,4,5,5,6,6]
print("type of list",type(lst))
arr =np.array(lst)
print(arr)
print("type of array",type(arr))

type of list <class 'list'>
[1 2 3 4 5 5 6 6]
type of array <class 'numpy.ndarray'>


In [10]:
arr =np.array(list(range(1,21)))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
arr =np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.zeros((5,10))  # 5 row and 10 column

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
arr =np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
# 1 d array convert into 2d array
arr = np.arange(0,30)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [20]:
arr.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [21]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [22]:
arr =np.random.randint(1,5,9)
arr

array([3, 1, 1, 4, 4, 1, 4, 4, 4], dtype=int32)

In [23]:
arr =np.random.randint(1,5,(3,3))
arr

array([[2, 2, 2],
       [2, 3, 2],
       [3, 3, 1]], dtype=int32)

In [24]:
arr = np.random.random(10)
arr

array([0.65694418, 0.2685687 , 0.80687864, 0.20415004, 0.65280997,
       0.27075324, 0.19026169, 0.00111874, 0.49385351, 0.3216105 ])

In [25]:
arr = np.random.random((5,10))
arr

array([[0.81633468, 0.5750092 , 0.69079948, 0.23892485, 0.87450397,
        0.1248855 , 0.20359682, 0.45940556, 0.81693658, 0.07202977],
       [0.77301194, 0.44537309, 0.78706876, 0.07816917, 0.8799185 ,
        0.75925648, 0.60441999, 0.13532043, 0.49843141, 0.34176707],
       [0.5264652 , 0.88304774, 0.22014682, 0.46982065, 0.62859305,
        0.15190785, 0.81062782, 0.83609552, 0.21889192, 0.12135565],
       [0.22005063, 0.25662186, 0.24324239, 0.79713621, 0.93272115,
        0.40740112, 0.82745205, 0.39689305, 0.55224682, 0.84265323],
       [0.71527546, 0.31400631, 0.79710895, 0.36164569, 0.25244359,
        0.11314703, 0.91274114, 0.59210453, 0.23903686, 0.58346697]])

In [26]:
arr =np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [27]:
print("shape of array:-",arr.shape)
print("size of array",arr.size)
print("data types:-",arr.dtype)
print("number of dimension",arr.ndim)

shape of array:- (12, 5)
size of array 60
data types:- int64
number of dimension 2


In [28]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [29]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [30]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [31]:
arr.shape

(12, 5)

In [32]:
arr.T.shape

(5, 12)

In [33]:
arr =np.arange(30)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
arr[12]

np.int64(12)

In [35]:
arr[0:12]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
arr[0]=100

In [37]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [38]:
arr =np.arange(60).reshape(12,5)

In [39]:
arr[1,3:5]

array([8, 9])

In [40]:
arr[1,1]

np.int64(6)

In [41]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [42]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [43]:
arr[1,1]=100

In [44]:
arr

array([[  0,   1,   2,   3,   4],
       [  5, 100,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [45]:
arr[11,4]

np.int64(59)

In [46]:
arr[-1][-1]

np.int64(59)

In [47]:
arr[11][-1]

np.int64(59)

In [48]:
arr[-1,-1]

np.int64(59)

In [49]:
arr = np.array(np.arange(225).reshape(5,15,3))

In [50]:
arr.ndim,arr.shape,arr.size,arr.dtype

(3, (5, 15, 3), 225, dtype('int64'))

In [51]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [52]:
arr[0,2:,2]

array([ 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [53]:
arr[0,3:5]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [54]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [55]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [56]:
arr[0,1,1]= 1000

In [57]:
arr[0,1,1]

np.int64(1000)

In [58]:
arr =np.array([1,5,6,9,2,3])

In [59]:
arr.sort()


In [60]:
arr

array([1, 2, 3, 5, 6, 9])

In [61]:
arr+2

array([ 3,  4,  5,  7,  8, 11])

In [62]:
arr-2

array([-1,  0,  1,  3,  4,  7])

In [63]:
arr*2

array([ 2,  4,  6, 10, 12, 18])

In [64]:
arr/2

array([0.5, 1. , 1.5, 2.5, 3. , 4.5])

In [65]:
arr1 = np.array([1,2,3,5])
arr2 =np.array([1,6,3,5])

In [66]:
#arr1+arr2
#arr1*arr2
arr1-arr2

array([ 0, -4,  0,  0])